#!/usr/bin/env bash

# ==========================================
# NEXUS - Local Infrastructure CLI
# ==========================================

# --- Constants & Configuration ---
readonly BOLD=$(tput bold)
readonly BLACK=$(tput setaf 0)
readonly RED=$(tput setaf 1)
readonly GREEN=$(tput setaf 2)
readonly YELLOW=$(tput setaf 3)
readonly CYAN=$(tput setaf 6)
readonly RESET=$(tput sgr0)
readonly THRESHOLD=75

# --- Helper Functions ---

print_header() {
    printf "${BOLD}:: %s ::${RESET}\n" "$1"
}


cleanup() {
    tput cnorm
    tput rmcup
    exit 0
}

# --- Status Function ---

get_disk_usage() {
    df -h | awk ' /\/$/ { print $5 }' | sed 's/%//'
}

get_ram_usage() {
    free -m | awk '/Mem:/ { printf "%.0f", $3/$2 * 100 }'
}

get_docker_count() {
    docker ps -q | wc -l
}

get_load_usage() {
    awk -v c="$(nproc)" '{printf "%.2f %.2f %.2f", $1/c, $2/c, $3/c}' /proc/loadavg
}

progress_bar() {
    local bar_length=20
    local num_bars=$(( $1 * bar_length / 100 ))
    local warning_bars=$((50 * bar_length / 100 - 1))
    local threshold_bars=$(($THRESHOLD * bar_length / 100 - 1))
    local bar="[$GREEN"

    local i
    for ((i = 0; i < num_bars; i++)); do
        if [[ i -eq warning_bars ]]; then
            bar+=$YELLOW
        elif [[ i -eq threshold_bars ]]; then
            bar+=$RED
        fi
        bar+="█"
        # bar+="|"
    done
    bar+="$RESET"
    for ((;i < bar_length; i++)); do
        bar+=" "
    done

    bar+="]"

    echo "$bar"
}

draw_stat() {
    local info="$1"

    # Get 5 minute value if info is for LOAD as it provides 3 values
    # Else use the provided argument
    if [[ "$info" != "LOAD" ]]; then
        local calc_val="$2"
        local display_val="$2"
    else
        local display_val=$(echo "$2" | awk '{ print $2 }')
        local calc_val=$(awk -v a="$display_val" 'BEGIN { print a * 100 }')  # Make into a whole number for progress bar calculation
    fi

    local val_color=$GREEN
    if [[ $calc_val -ge $THRESHOLD ]]; then
        val_color=$RED
    fi

    printf "  %-5s %s ${BOLD}$val_color%3s" "$info" "$(progress_bar ${calc_val})" "${display_val}"

    case $info in
        LOAD)   echo " ${RESET}($2)";;  # Prints the three loads ex. (0.11 0.12 0.12)
        *) echo "%";;  # Prints out % for Disk and Ram
    esac

    echo -n $RESET
}

draw_docker_stat() {
    local docker_count="$1"

    if [[ docker_count -gt 0 ]]; then
        status="${BOLD}${GREEN}Running${RESET}"
    else
        status="${BOLD}${CYAN}Sleep Mode${RESET}"
    fi

    echo "----------------------------------------------------"

    local clean_str="$docker_count (Status: $status)"
    local pad_len=$((43 - ${#clean_str}))

        printf "  %-15s  %*s${BOLD}%s${RESET} (Status: %s)\n" \
            "Docker Containers:" \
            $pad_len "" \
            "$docker_count" \
            "$status"

        echo "----------------------------------------------------"
}

display_status_dashboard() {
    tput home
    print_header "NEXUS SYSTEM DASHBOARD"
    echo 

    draw_stat "RAM" "$1"
    draw_stat "DISK" "$2"
    draw_stat "LOAD" "$3"

    echo 
    draw_docker_stat "$4"

    tput cup $((LINES - 1)) 0
}

status_controller() {
    tput home


    while true; do
        tput cup 1 0
        display_status_dashboard "$(get_ram_usage)" "$(get_disk_usage)" "$(get_load_usage)" "$(get_docker_count)"

        read -t 1 -p "Press Q to quit: " -N 1 -s key
        [[ $key == q ]] && cleanup
    done

    return 0
}

# =====================
# === Service Logic ===
# =====================

# --- Models Functions ---

stop_service() {
    sudo systemctl stop "$1"
    sleep 1
}

kill_service() {
    local service="$1"
    if [[ "$service" == "bluetooth" ]]; then
        sudo rfkill block bluetooth
    fi

    stop_service "$service"
    sleep 1
}

enable_service() {
    local service="$1"
    if [[ "$service" == "bluetooth" ]]; then
        sudo rfkill unblock bluetooth
    fi

    sudo systemctl start "$service"
    sleep 1
}

is_valid_service() {
    case "$1" in
        bt|bluetooth|docker) return 0;;
        *) return 1;;
    esac
}

get_requested_service() {
    local service="$1"

    case "$service" in
        bt|bluetooth) echo "Bluetooth";;
        docker) echo "Docker";;
        *) return 1;;
    esac
}

get_service_status() {
    systemctl is-active "$1" | tr '[:lower:]' '[:upper:]'
}

get_rf_status() {
    local rf_status=""
    if [[ "$1" == "Bluetooth" ]]; then
        if rfkill list bluetooth | grep -q "Soft blocked: yes"; then
            rf_status="${RED}[BLOCKED]${RESET}"
        else
            rf_status="${GREEN}[UNBLOCKED]${RESET}"
        fi
    fi

    echo "$rf_status"
    return 0
}

# -- View Functions ---

display_service_dashboard() {
    tput home 
    tput ed

    local target_service="$1"
    local status="$2"
    local rf_status="$3"

    if [[ "$status" == "ACTIVE" ]]; then
        status="${GREEN}${status}${RESET}"
    else
        status="${RED}${status}${RESET}"
    fi

    print_header "NEXUS SERVICE CONTROL" 

    echo
    printf "  %-20s ${BOLD}${CYAN}%s${RESET}\n" "TARGET:" "$target_service"
    printf "  %-20s ${BOLD}%s${RESET}\n" "STATUS:" "$status"
    if [[ -n "$rf_status" ]]; then
        printf "  %-20s ${BOLD}%s${RESET}\n" "RADIO:" "$rf_status"
    fi

    echo ""
    echo "------------------------------------------"
    echo "   [1] Enable Service (Turn On)"
    echo "   [2] Stop Service (Turn Off)"
    [[ "$target_service" == "Bluetooth" ]] && echo "   [3] Kill Service (Stop Service and Radio)"
    echo "   [q] Quit"
    echo ""
}

# --- Controller Function ---

service_controller() {
    local target_service="$1"

    while true; do
        local status=$(get_service_status "$target_service")
        local rf_status=$(get_rf_status "$target_service")

        display_service_dashboard "$target_service" "$status" "$rf_status"


        read -N 1 -p "Select action: " key
        tput ed
        echo


        case "$key" in
            1)  echo "${GREEN}Enabling $target_service...${RESET}"
                enable_service "${target_service,}"
                ;;
            2)  echo "${RED}Stopping $target_service...${RESET}"
                stop_service "${target_service,}"
                ;;
            3)  echo "${RED}Killing $target_service...${RESET}"
                kill_service "${target_service,}"
                ;;
            q) cleanup;;
        esac
    done
}

with_tui() {
    local controller_func=$1
    local args="${@:2}"

    tput smcup
    tput civis

    trap cleanup SIGINT

    "$controller_func" "$args"

    tput rmcup
    tput cnorm
}

# --- Main Controller ---

trap cleanup SIGINT

command=${1:-help}

case "$command" in
    status)
        with_tui status_controller
        ;;
    service)
        if [[ -z "$2" ]]; then
            echo "Usage: nexus control [bt|docker]"
            return 1
        fi

        target_service=$(get_requested_service "$2") || { 
            echo "${RED}Error: '$2' is not a supported service.${RESET}" >&2 
            exit 1
        }
        with_tui service_controller "$target_service"
        ;;
    new)
        echo "Running new command"
        ;;
    help|--help|-h)
        print_header "NEXUS HELP"
        echo "  status              Open System Dashboard"
        echo "  service <service>   Kill service on systemctl"
        echo "  new <type> <name>   Create new project (python/bash)"
        ;;
    *)
        echo "Error: Unknown command '$1'" >&2
        echo "Usage: nexus [status|service|new]" >&2
        exit 1
        ;;
esac
