#!/usr/bin/env bash

# ==========================================
# NEXUS - Local Infrastructure CLI
# ==========================================

# --- Constants & Configuration ---
readonly BOLD=$(tput bold)
readonly BLACK=$(tput setaf 0)
readonly RED=$(tput setaf 1)
readonly GREEN=$(tput setaf 2)
readonly YELLOW=$(tput setaf 3)
readonly CYAN=$(tput setaf 6)
readonly RESET=$(tput sgr0)
readonly THRESHOLD=75

# --- Helper Functions ---

print_header() {
    printf "${BOLD}:: %s ::${RESET}\n" "$1"
}


cleanup() {
    tput cnorm
    tput rmcup
    exit 1
}

get_disk_usage() {
    disk_usage=$( df -h | awk ' /\/$/ { print $5 }' | sed 's/%//')
    echo "$disk_usage"
}

get_ram_usage() {
    ram_usage_perc=$( free -m | awk '/Mem:/ { printf "%.0f", $3/$2 * 100 }')
    echo "$ram_usage_perc"
}

get_docker_count() {
    docker_count=$( docker ps -q | wc -l )
    echo "$docker_count"
}

get_load_usage() {
    local cores=$(nproc)
    local loads=$(awk -v c="$cores" '{printf "%.2f %.2f %.2f", $1/c, $2/c, $3/c}' /proc/loadavg)
    echo "$loads"
}

progress_bar() {
    local bar_length=20
    local num_bars=$(( $1 * bar_length / 100 ))
    local warning_bars=$((50 * bar_length / 100 - 1))
    local threshold_bars=$(($THRESHOLD * bar_length / 100 - 1))
    local bar="[$GREEN"

    local i
    for ((i = 0; i < num_bars; i++)); do
        if [[ i -eq warning_bars ]]; then
            bar+=$YELLOW
        elif [[ i -eq threshold_bars ]]; then
            bar+=$RED
        fi
        bar+="█"
        # bar+="|"
    done
    bar+="$RESET"
    for ((;i < bar_length; i++)); do
        bar+=" "
        # bar+="░"
    done

    bar+="]"

    echo "$bar"
}

print_stat() {
    info="$1"
    val="$2"

    val_color=$GREEN
    if [[ $val -ge $THRESHOLD ]]; then
        val_color=$RED
    fi

    printf "%-5s %s ${BOLD}$val_color%3s" "$info" "$(progress_bar $val)" "$val"

    case $info in
        LOAD)   echo "(Low)";;
        *) echo "%";;
    esac

    echo -n $RESET
}

show_status() {
    tput home

    tput cup 1 1
    print_header "NEXUS SYSTEM DASHBOARD"

    while true; do
        tput cup 3 1
        # print_stat "RAM" "$(get_ram_usage)"
        # print_stat "DISK" "$(get_disk_usage)"
        print_stat "RAM" "$(($RANDOM % (100 - 1 + 1) + 1))"
        tput cup 4 1
        print_stat "DISK" "$(($RANDOM % (100 - 1 + 1) + 1))"

        tput cup 6 1
        # docker_count=$(get_docker_count)
        docker_count=$(($RANDOM % (5 - 0 + 1) + 0))
        if [[ docker_count -gt 0 ]]; then
            status="${BOLD}${GREEN}Running${RESET}"
        else
            status="${BOLD}${CYAN}Sleep Mode${RESET}"
        fi

        echo "---------------------------------------------"
        clean_str="$docker_count (Status: $status)"

        pad_len=$((40 - ${#clean_str}))

        tput cup 7 1
        printf "%-15s  %*s${BOLD}%s${RESET} (Status: %s)\n" \
          "Docker Containers:" \
          $pad_len "" \
          "$docker_count" \
          "$status"
        echo " ---------------------------------------------"

        tput cup $((LINES - 1)) 0
        read -t 1 -p "Press Q to quit: " -N 1 -s key


        if [[ $key == q ]]; then
            cleanup
        fi

    done

    # while true; do
    #     tput cup 3 1
    #     # print_stat "RAM" "$(get_ram_usage)"
    #     # print_stat "DISK" "$(get_disk_usage)"
    #     print_stat "RAM" "$(($RANDOM % (100 - 1 + 1) + 1))"
    #     tput cup 4 1
    #     print_stat "DISK" "$(($RANDOM % (100 - 1 + 1) + 1))"
    #
    #     tput cup $((LINES - 1)) 0
    #     read -t 1 -p "Press Q to quit: " -N 1 -s key
    #
    #     if [[ $key == q ]]; then
    #         cleanup
    #     fi
    #
    # done
    
    return 0

}

trap cleanup SIGINT


tput smcup; tput civis
show_status
